//app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoalProvider } from "@/lib/goal-store";

import { GoogleOAuthProvider } from '@react-oauth/google';
import { AuthProvider } from "@/lib/auth-context";
import { CalendarProvider } from "@/lib/calendar-store";
import { Toaster } from "@/components/ui/toaster"
import { ProfileProvider } from "@/lib/profile-store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Goal Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  // Debug logging for development
  if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
    console.log('Google Client ID configured:', clientId ? 'Yes' : 'No');
    console.log('Current origin:', window.location.origin);
  }

  if (!clientId) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <div className="flex h-screen items-center justify-center">
             <h1 className="text-red-500 font-bold text-2xl">Configuration Error: Google Client ID is missing.</h1>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={clientId}>
          <AuthProvider>
            <ProfileProvider>
              <GoalProvider>
                <CalendarProvider>
                  {children}
                </CalendarProvider>
              </GoalProvider>
            </ProfileProvider>
            <Toaster />
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}